# Generated by Django 2.2.1 on 2020-04-21 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('brewer', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('serving_type', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
