# Generated by Django 2.2.1 on 2020-04-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alcohol',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='bitter',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='beer',
            name='burnt',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='dry',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='beer',
            name='floral',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='beer',
            name='herbal',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='hoppy',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='beer',
            name='linger',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='malty',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='sour',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='beer',
            name='spicy',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='beer',
            name='sweet',
            field=models.FloatField(default=10),
        ),
    ]
