# Generated by Django 2.2.1 on 2020-04-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20200430_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(default=6, verbose_name='ABV'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='ibu',
            field=models.FloatField(default=70, verbose_name='IBU'),
        ),
    ]
